server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
polar:
  greeting: Hello World from local book catalog!
